Taskman/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Taskman.Web.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

}

Taskman/Models/IssueModel.cs
using System;

namespace Taskman.Web.Models
{
    public class IssueModel
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int IssueStateId { get; set; }
        public string Name { get; set; }
        public DateTime DateCreate { get; set; }
        public string Description { get; set; }
        public bool Executed { get; set; }
    }
}

Taskman/Models/IssueStateModel.cs
using System;

namespace Taskman.Web.Models
{
    public class IssueStateModel
    {
        public int Id { get; set; } 

        public string Name { get; set; }
    }
}

Taskman/Models/IssuesModel.cs
using System;
using System.Collections.Generic;

namespace Taskman.Web.Models
{
    public class IssuesModel
    {
        public IEnumerable<IssueModel> IssueModels { get; set; }
        public int Count { get; set; }
    }
}

Taskman/Controllers/AccountController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Taskman.Core;
using Taskman.Web.Models;

namespace Taskman.Web.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly IUserRepocitory _userRepocitory;
        
        public AccountController(IUserRepocitory userRepocitory)
        {
            _userRepocitory = userRepocitory;
        }
       
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userRepocitory.SignIn(model.Username, model.Password);
            if (user != null)
            {
                var authTicket = new FormsAuthenticationTicket(
                    1,
                    model.Username,
                    DateTime.Now,
                    DateTime.Now.AddMinutes(60),
                    true,
                    user.Id.ToString()
                    );
                var encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                Response.Cookies.Add(authCookie);

                if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                    && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\") && !returnUrl.ToLower().Contains("logoff"))
                {
                    return Redirect(returnUrl);
                }

                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "User Name and/or Password you entered is not correct. Please try again.");

            return View(model);
        }
      
        
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();

            // clear authentication cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);

            // clear session cookie
            HttpCookie cookie2 = new HttpCookie("ASP.NET_SessionId", "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);

            return RedirectToAction("Index", "Home");
        }
    }
}

Taskman/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Taskman.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: Issue
        public ActionResult Index()
        {
            return View();
        }
    }
}

Taskman/Controllers/IssueStateController.cs
using System.Web.Mvc;

namespace Taskman.Web.Controllers
{
    [Authorize]
    public class IssueStateController : Controller
    {
        // GET: IssueState
        public ActionResult Index()
        {
            return View();
        }
    }
}

Taskman/Views/Home/Index.cshtml
@{ Html.RenderPartial("~/Components/issue.cshtml"); }

@section style
{
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/base/jquery-ui.css"/>
    <script src="~/Ko/ko.jquery.datepicker.js"></script>
}

<div>
    <div class="container">
        <div class="row" data-bind="if: canAdd">
            <button class="btn btn-default glyphicon-plus" data-bind="click: addItem">AddNewIssue</button>
        </div>
        <div class="row filter">
            <div class="col-md-1">
                <select class="input form-control" title="Executed filter"
                        data-bind="value: filter.Executed, options: executedList,
                                optionsText: 'Name',  optionsValue: 'Value'"></select>
            </div>
            <div class="col-md-2">
                <select class="input form-control" title="Issue State filter"
                        data-bind="value: filter.IssueStateId, options: issueStatesForFilter,
                                optionsText: 'Name',  optionsValue: 'Id'"></select>
            </div>
            <div class="col-md-3">
                <input type="date" class="input form-control" placeholder="Name filter" title="Name filter"
                       data-bind="value: filter.Name"/>
            </div>
            <div class="col-md-2">
                <input class="input form-control" placeholder="Date create filter" title="Date create filter"
                       data-bind="datepicker: filter.DateCreate, datepickerOptions: { dateFormat: 'yy-mm-dd' }"/>
            </div>
            <div class="col-md-3">
                <input type="date" class="input form-control" placeholder="Description filter" title="Description filter"
                       data-bind="value: filter.Description"/>
            </div>
            <div class="col-md-1">
                <button class="btn btn-default glyphicon glyphicon-filter" type="button" data-bind="click: loadIssues" title="Filter"></button>
            </div>
        </div>

        <div class="row">
            <div class="col-md-1">
                <label for="count">Count:</label>
                <label id="count" data-bind="text: paging.count"></label>
            </div>

            <div class="col-md-2" data-bind="foreach: paging.pages">
                <span data-bind="if: isSelected">[</span>
                <a style="cursor: default" data-bind="text: link, click: href"></a>
                <span data-bind="if: isSelected">]</span>
            </div>

            <div class="col-md-2">
                <label for="pageSize">Page Size: </label>
                <select id="pageSize" class="input " title="Issue State"
                        data-bind="value: paging.pageSize, options: paging.pageSizes"></select>
            </div>
           
        </div>
        <div class="row" data-bind="foreach: issues">
            <div data-bind="component: {name: 'issue', params: $data}"></div>
        </div>
       
    </div>
</div>


@section scripts
{
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.js"></script>
    <script src="~/Ko/Components/issue.js"></script>
    <script src="~/Ko/Db/issuesImpl.js"></script>
    <script src="~/Ko/Db/issueStatesImpl.js"></script>
    <script src="~/Ko/Controllers/Home/Index.js"></script>
}

Taskman/Views/IssueState/Index.cshtml
@{ Html.RenderPartial("~/Components/issueState.cshtml"); }


<div>
    <div class="container">
        <div class="row" data-bind="if: canAdd">
            <button class="btn btn-default" data-bind="click: addItem">Add New</button>
        </div>
        <div class="row">
            <div class="col-md-1">
                <span>Id</span>
            </div>
            <div class="col-md-5">
                <span>Name</span>
            </div>
        </div>
        <div class="row" data-bind="foreach: issueStates">
            <div data-bind="component: {name: 'issue_state', params: $data}"></div>
        </div>
    </div>
</div>


@section scripts
{
    <script src="~/Ko/Components/issueState.js"></script>
    <script src="~/Ko/Db/issueStatesImpl.js"></script>
    <script src="~/Ko/Controllers/IssueState/Index.js"></script>
}

Taskman/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taskman</title>

    <script src="//code.jquery.com/jquery-2.2.0.js"></script>

    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/knockout/knockout-3.3.0.js"></script>

    @RenderSection("style", required: false)
    @functions{
        public string BaseUrl()
        {
            var temp = new Uri(Request.Url, Url.Content("~"));
            return temp.ToString();
        }
    }
    <script type="text/javascript">
        function getBaseUrl() {
            return '@BaseUrl()';
        }
    </script>
    

</head>
<body>
    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Issues", "Index", "Home")</li>
                    <li>@Html.ActionLink("Importance", "Index", "IssueState")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>